### ISSUE TITLE
Use React Create Context ?

### ISSUE THREAD

**Issue by stelone** [nurzhan-saktaganov/react-rbac#4]
Is there any reason to not use React.createContext (see : https://fr.reactjs.org/docs/context.html) ?

**Comment by nurzhan-saktaganov** [comment]
As you can see here, it already tries to use React.createContext if possible. See:
https://github.com/nurzhan-saktaganov/react-rbac-guard/blob/2c52084129b23efc3fd68d9311b38fb0af426e23/src/createContext.jsx#L75

But the new context API, which provides React.createContext, was introduced with version 16.3 of ReactJS (see: https://reactjs.org/docs/legacy-context.html).

So, I tried to make it compatible with the older versions of ReactJS too.
